import { HugeiconsIcon, type IconSvgElement } from "@hugeicons/react";
import {
  Airplane01Icon,
  Alien01Icon,
  Analytics01Icon,
  AnchorIcon,
  Atom01Icon,
  BankIcon,
  BatteryFullIcon,
  BeachIcon,
  Bicycle01Icon,
  BluetoothIcon,
  Book02Icon,
  BookOpen01Icon,
  Briefcase01Icon,
  Bug01Icon,
  BulbIcon,
  Building01Icon,
  Bus01Icon,
  CalculatorIcon,
  Camera01Icon,
  Car01Icon,
  Castle01Icon,
  ChartLineData01Icon,
  ChipIcon,
  City01Icon,
  CloudIcon,
  CloudServerIcon,
  CodeIcon,
  Coffee01Icon,
  Compass01Icon,
  CpuIcon,
  CreditCardIcon,
  CrownIcon,
  Database01Icon,
  DiamondIcon,
  DiceIcon,
  DnaIcon,
  DollarCircleIcon,
  DropletIcon,
  EarthIcon,
  FavouriteIcon,
  Film01Icon,
  Fire02Icon,
  Flag01Icon,
  FlashIcon,
  FlowerIcon,
  GameController01Icon,
  GiftIcon,
  GitBranchIcon,
  GithubIcon,
  GlobalIcon,
  GraduationScrollIcon,
  HappyIcon,
  HardDriveIcon,
  HeadphonesIcon,
  HelicopterIcon,
  Home01Icon,
  Idea01Icon,
  Image01Icon,
  Key01Icon,
  Leaf01Icon,
  LockIcon,
  MagicWand01Icon,
  MapPinIcon,
  Medal01Icon,
  Mic01Icon,
  MicroscopeIcon,
  Money01Icon,
  Moon02Icon,
  MountainIcon,
  MusicNote01Icon,
  Notebook01Icon,
  PackageIcon,
  PaintBrush01Icon,
  PaintBucketIcon,
  PencilIcon,
  PieChartIcon,
  PillIcon,
  PizzaIcon,
  Plug01Icon,
  PuzzleIcon,
  Radar01Icon,
  Robot01Icon,
  Rocket01Icon,
  RulerIcon,
  SatelliteIcon,
  SaturnIcon,
  ScissorIcon,
  Settings01Icon,
  Shield01Icon,
  ShoppingCart01Icon,
  SkullIcon,
  SmileIcon,
  SnowIcon,
  SparklesIcon,
  StarIcon,
  Stethoscope02Icon,
  Store01Icon,
  Sun03Icon,
  Target02Icon,
  Telescope01Icon,
  TentIcon,
  TerminalIcon,
  TestTube01Icon,
  Train01Icon,
  Tree01Icon,
  TruckIcon,
  Ufo01Icon,
  UmbrellaIcon,
  UserGroupIcon,
  UserIcon,
  Video01Icon,
  Wallet01Icon,
  Wifi01Icon,
  Wrench01Icon,
  ZapIcon,
} from "@hugeicons/core-free-icons";
import { cn } from "../lib/utils";

export interface ProjectGlyph {
  name: string;
  icon: IconSvgElement;
  keywords: readonly string[];
}

// Decorative glyphs a repository can be badged with — separate from the UI
// chrome set in components/ui/icon.tsx so picker choices survive UI icon
// renames. Stored customizations reference these by `name`.
export const PROJECT_GLYPHS: readonly ProjectGlyph[] = [
  { name: "Home", icon: Home01Icon, keywords: ["home", "house"] },
  { name: "Rocket", icon: Rocket01Icon, keywords: ["rocket", "launch", "ship", "space"] },
  { name: "Star", icon: StarIcon, keywords: ["star", "favorite"] },
  { name: "Heart", icon: FavouriteIcon, keywords: ["heart", "love", "favorite"] },
  { name: "Zap", icon: ZapIcon, keywords: ["zap", "bolt", "energy"] },
  { name: "Flash", icon: FlashIcon, keywords: ["flash", "lightning", "fast"] },
  { name: "Fire", icon: Fire02Icon, keywords: ["fire", "flame", "hot"] },
  { name: "Sparkles", icon: SparklesIcon, keywords: ["sparkles", "magic", "ai", "new"] },
  { name: "MagicWand", icon: MagicWand01Icon, keywords: ["magic", "wand", "wizard"] },
  { name: "Crown", icon: CrownIcon, keywords: ["crown", "king", "queen", "royal"] },
  { name: "Diamond", icon: DiamondIcon, keywords: ["diamond", "gem", "jewel"] },
  { name: "Trophy", icon: Medal01Icon, keywords: ["medal", "trophy", "award", "winner"] },
  { name: "Flag", icon: Flag01Icon, keywords: ["flag", "milestone", "goal"] },
  { name: "Target", icon: Target02Icon, keywords: ["target", "goal", "aim", "focus"] },
  { name: "Code", icon: CodeIcon, keywords: ["code", "developer", "brackets"] },
  { name: "Terminal", icon: TerminalIcon, keywords: ["terminal", "console", "cli", "shell"] },
  { name: "GitBranch", icon: GitBranchIcon, keywords: ["git", "branch", "version"] },
  { name: "Github", icon: GithubIcon, keywords: ["github", "octocat", "repo"] },
  { name: "Bug", icon: Bug01Icon, keywords: ["bug", "insect", "debug"] },
  { name: "Chip", icon: ChipIcon, keywords: ["chip", "hardware", "circuit"] },
  { name: "Cpu", icon: CpuIcon, keywords: ["cpu", "processor", "compute"] },
  { name: "Database", icon: Database01Icon, keywords: ["database", "storage", "sql"] },
  { name: "HardDrive", icon: HardDriveIcon, keywords: ["disk", "drive", "storage"] },
  { name: "CloudServer", icon: CloudServerIcon, keywords: ["server", "cloud", "hosting"] },
  { name: "Cloud", icon: CloudIcon, keywords: ["cloud", "sky", "weather"] },
  { name: "Robot", icon: Robot01Icon, keywords: ["robot", "bot", "ai", "agent"] },
  { name: "Radar", icon: Radar01Icon, keywords: ["radar", "scan", "monitor"] },
  { name: "Satellite", icon: SatelliteIcon, keywords: ["satellite", "orbit", "signal"] },
  { name: "Wifi", icon: Wifi01Icon, keywords: ["wifi", "wireless", "network"] },
  { name: "Bluetooth", icon: BluetoothIcon, keywords: ["bluetooth", "wireless"] },
  { name: "Battery", icon: BatteryFullIcon, keywords: ["battery", "power", "charge"] },
  { name: "Plug", icon: Plug01Icon, keywords: ["plug", "power", "integration"] },
  { name: "Settings", icon: Settings01Icon, keywords: ["settings", "gear", "config"] },
  { name: "Wrench", icon: Wrench01Icon, keywords: ["wrench", "tool", "fix"] },
  { name: "Ruler", icon: RulerIcon, keywords: ["ruler", "measure", "design"] },
  { name: "Scissors", icon: ScissorIcon, keywords: ["scissors", "cut", "trim"] },
  { name: "Key", icon: Key01Icon, keywords: ["key", "auth", "secret", "access"] },
  { name: "Lock", icon: LockIcon, keywords: ["lock", "security", "private"] },
  { name: "Shield", icon: Shield01Icon, keywords: ["shield", "security", "protect"] },
  { name: "Package", icon: PackageIcon, keywords: ["package", "box", "shipping", "npm"] },
  { name: "Puzzle", icon: PuzzleIcon, keywords: ["puzzle", "plugin", "piece"] },
  { name: "Dice", icon: DiceIcon, keywords: ["dice", "game", "random"] },
  { name: "GameController", icon: GameController01Icon, keywords: ["game", "controller", "play"] },
  { name: "Book", icon: Book02Icon, keywords: ["book", "docs", "read"] },
  { name: "BookOpen", icon: BookOpen01Icon, keywords: ["book", "open", "docs", "learn"] },
  { name: "Notebook", icon: Notebook01Icon, keywords: ["notebook", "notes", "journal"] },
  { name: "Graduation", icon: GraduationScrollIcon, keywords: ["graduation", "school", "learn", "education"] },
  { name: "Pencil", icon: PencilIcon, keywords: ["pencil", "write", "draft"] },
  { name: "PaintBrush", icon: PaintBrush01Icon, keywords: ["paint", "brush", "art", "design"] },
  { name: "PaintBucket", icon: PaintBucketIcon, keywords: ["paint", "bucket", "fill", "color"] },
  { name: "Camera", icon: Camera01Icon, keywords: ["camera", "photo", "picture"] },
  { name: "Image", icon: Image01Icon, keywords: ["image", "photo", "gallery"] },
  { name: "Film", icon: Film01Icon, keywords: ["film", "movie", "video"] },
  { name: "Video", icon: Video01Icon, keywords: ["video", "record", "camera"] },
  { name: "Music", icon: MusicNote01Icon, keywords: ["music", "note", "song", "audio"] },
  { name: "Headphones", icon: HeadphonesIcon, keywords: ["headphones", "audio", "listen"] },
  { name: "Mic", icon: Mic01Icon, keywords: ["mic", "microphone", "voice", "podcast"] },
  { name: "Chart", icon: ChartLineData01Icon, keywords: ["chart", "line", "analytics", "growth"] },
  { name: "PieChart", icon: PieChartIcon, keywords: ["pie", "chart", "stats"] },
  { name: "Analytics", icon: Analytics01Icon, keywords: ["analytics", "data", "metrics"] },
  { name: "Calculator", icon: CalculatorIcon, keywords: ["calculator", "math", "numbers"] },
  { name: "Money", icon: Money01Icon, keywords: ["money", "cash", "bills"] },
  { name: "Dollar", icon: DollarCircleIcon, keywords: ["dollar", "money", "finance"] },
  { name: "CreditCard", icon: CreditCardIcon, keywords: ["credit", "card", "payment", "billing"] },
  { name: "Bank", icon: BankIcon, keywords: ["bank", "finance", "institution"] },
  { name: "Wallet", icon: Wallet01Icon, keywords: ["wallet", "money", "pay"] },
  { name: "Briefcase", icon: Briefcase01Icon, keywords: ["briefcase", "work", "business"] },
  { name: "ShoppingCart", icon: ShoppingCart01Icon, keywords: ["shopping", "cart", "store", "ecommerce"] },
  { name: "Store", icon: Store01Icon, keywords: ["store", "shop", "market"] },
  { name: "Building", icon: Building01Icon, keywords: ["building", "office", "company"] },
  { name: "City", icon: City01Icon, keywords: ["city", "skyline", "urban"] },
  { name: "Castle", icon: Castle01Icon, keywords: ["castle", "fortress", "kingdom"] },
  { name: "Tent", icon: TentIcon, keywords: ["tent", "camp", "outdoors"] },
  { name: "Gift", icon: GiftIcon, keywords: ["gift", "present", "reward"] },
  { name: "User", icon: UserIcon, keywords: ["user", "person", "profile"] },
  { name: "UserGroup", icon: UserGroupIcon, keywords: ["users", "group", "team", "people"] },
  { name: "Smile", icon: SmileIcon, keywords: ["smile", "happy", "face"] },
  { name: "Happy", icon: HappyIcon, keywords: ["happy", "joy", "face"] },
  { name: "Skull", icon: SkullIcon, keywords: ["skull", "danger", "pirate"] },
  { name: "Alien", icon: Alien01Icon, keywords: ["alien", "space", "ufo"] },
  { name: "Ufo", icon: Ufo01Icon, keywords: ["ufo", "space", "saucer"] },
  { name: "Saturn", icon: SaturnIcon, keywords: ["saturn", "planet", "space"] },
  { name: "Earth", icon: EarthIcon, keywords: ["earth", "world", "planet"] },
  { name: "Globe", icon: GlobalIcon, keywords: ["globe", "global", "world", "web"] },
  { name: "Moon", icon: Moon02Icon, keywords: ["moon", "night", "dark"] },
  { name: "Sun", icon: Sun03Icon, keywords: ["sun", "day", "light"] },
  { name: "Snow", icon: SnowIcon, keywords: ["snow", "winter", "cold"] },
  { name: "Umbrella", icon: UmbrellaIcon, keywords: ["umbrella", "rain", "cover"] },
  { name: "Droplet", icon: DropletIcon, keywords: ["droplet", "water", "liquid"] },
  { name: "Leaf", icon: Leaf01Icon, keywords: ["leaf", "nature", "eco", "green"] },
  { name: "Tree", icon: Tree01Icon, keywords: ["tree", "nature", "forest"] },
  { name: "Flower", icon: FlowerIcon, keywords: ["flower", "bloom", "garden"] },
  { name: "Mountain", icon: MountainIcon, keywords: ["mountain", "peak", "climb"] },
  { name: "Beach", icon: BeachIcon, keywords: ["beach", "vacation", "island"] },
  { name: "MapPin", icon: MapPinIcon, keywords: ["map", "pin", "location", "place"] },
  { name: "Compass", icon: Compass01Icon, keywords: ["compass", "navigate", "explore"] },
  { name: "Anchor", icon: AnchorIcon, keywords: ["anchor", "ship", "harbor"] },
  { name: "Airplane", icon: Airplane01Icon, keywords: ["airplane", "plane", "travel", "flight"] },
  { name: "Helicopter", icon: HelicopterIcon, keywords: ["helicopter", "fly", "chopper"] },
  { name: "Car", icon: Car01Icon, keywords: ["car", "drive", "auto"] },
  { name: "Bus", icon: Bus01Icon, keywords: ["bus", "transit", "transport"] },
  { name: "Truck", icon: TruckIcon, keywords: ["truck", "delivery", "shipping"] },
  { name: "Train", icon: Train01Icon, keywords: ["train", "rail", "transit"] },
  { name: "Bicycle", icon: Bicycle01Icon, keywords: ["bicycle", "bike", "cycle"] },
  { name: "Idea", icon: Idea01Icon, keywords: ["idea", "lightbulb", "brainstorm"] },
  { name: "Bulb", icon: BulbIcon, keywords: ["bulb", "light", "idea"] },
  { name: "Atom", icon: Atom01Icon, keywords: ["atom", "science", "physics"] },
  { name: "TestTube", icon: TestTube01Icon, keywords: ["test", "tube", "lab", "experiment"] },
  { name: "Microscope", icon: MicroscopeIcon, keywords: ["microscope", "science", "research"] },
  { name: "Telescope", icon: Telescope01Icon, keywords: ["telescope", "astronomy", "observe"] },
  { name: "Dna", icon: DnaIcon, keywords: ["dna", "biology", "genetics"] },
  { name: "Pill", icon: PillIcon, keywords: ["pill", "medicine", "health"] },
  { name: "Stethoscope", icon: Stethoscope02Icon, keywords: ["stethoscope", "doctor", "health"] },
  { name: "Coffee", icon: Coffee01Icon, keywords: ["coffee", "cup", "cafe"] },
  { name: "Pizza", icon: PizzaIcon, keywords: ["pizza", "food", "slice"] },
] as const;

const GLYPH_BY_NAME = new Map(
  PROJECT_GLYPHS.map((glyph) => [glyph.name, glyph]),
);

export interface ProjectEmoji {
  value: string;
  keywords: readonly string[];
}

export const PROJECT_EMOJI: readonly ProjectEmoji[] = [
  { value: "🚀", keywords: ["rocket", "launch", "ship"] },
  { value: "⭐", keywords: ["star", "favorite"] },
  { value: "✨", keywords: ["sparkles", "magic", "new"] },
  { value: "🔥", keywords: ["fire", "hot", "flame"] },
  { value: "⚡", keywords: ["zap", "lightning", "fast"] },
  { value: "💡", keywords: ["idea", "lightbulb"] },
  { value: "🎯", keywords: ["target", "goal", "dart"] },
  { value: "🏆", keywords: ["trophy", "winner", "award"] },
  { value: "👑", keywords: ["crown", "king", "queen"] },
  { value: "💎", keywords: ["diamond", "gem"] },
  { value: "🧪", keywords: ["test", "lab", "experiment"] },
  { value: "🔬", keywords: ["microscope", "science"] },
  { value: "🔭", keywords: ["telescope", "astronomy"] },
  { value: "🧬", keywords: ["dna", "biology"] },
  { value: "🤖", keywords: ["robot", "bot", "ai", "agent"] },
  { value: "👻", keywords: ["ghost", "spooky", "boo"] },
  { value: "👾", keywords: ["alien", "game", "invader"] },
  { value: "🛸", keywords: ["ufo", "saucer", "space"] },
  { value: "🌙", keywords: ["moon", "night"] },
  { value: "☀️", keywords: ["sun", "day"] },
  { value: "🌈", keywords: ["rainbow", "color", "pride"] },
  { value: "🌊", keywords: ["wave", "ocean", "sea"] },
  { value: "🌱", keywords: ["seedling", "sprout", "grow"] },
  { value: "🌲", keywords: ["tree", "evergreen", "forest"] },
  { value: "🌸", keywords: ["blossom", "flower", "spring"] },
  { value: "🍀", keywords: ["clover", "luck", "four leaf"] },
  { value: "🏔️", keywords: ["mountain", "peak", "snow"] },
  { value: "🏝️", keywords: ["island", "beach", "vacation"] },
  { value: "🌋", keywords: ["volcano", "eruption"] },
  { value: "🪐", keywords: ["saturn", "planet", "space"] },
  { value: "🌍", keywords: ["earth", "globe", "world"] },
  { value: "🧭", keywords: ["compass", "navigate", "explore"] },
  { value: "🗺️", keywords: ["map", "world", "travel"] },
  { value: "📍", keywords: ["pin", "location", "place"] },
  { value: "⚓", keywords: ["anchor", "ship", "harbor"] },
  { value: "✈️", keywords: ["airplane", "plane", "travel"] },
  { value: "🚁", keywords: ["helicopter", "chopper"] },
  { value: "🚗", keywords: ["car", "drive", "auto"] },
  { value: "🚌", keywords: ["bus", "transit"] },
  { value: "🚚", keywords: ["truck", "delivery"] },
  { value: "🚂", keywords: ["train", "locomotive", "rail"] },
  { value: "🚲", keywords: ["bicycle", "bike", "cycle"] },
  { value: "🛰️", keywords: ["satellite", "orbit", "signal"] },
  { value: "💻", keywords: ["laptop", "computer", "code"] },
  { value: "🖥️", keywords: ["desktop", "computer", "monitor"] },
  { value: "⌨️", keywords: ["keyboard", "type", "input"] },
  { value: "🖱️", keywords: ["mouse", "click", "cursor"] },
  { value: "💾", keywords: ["floppy", "save", "disk"] },
  { value: "📀", keywords: ["dvd", "disc", "media"] },
  { value: "🔌", keywords: ["plug", "power", "integration"] },
  { value: "🔋", keywords: ["battery", "power", "charge"] },
  { value: "📡", keywords: ["antenna", "signal", "broadcast"] },
  { value: "🧲", keywords: ["magnet", "attract"] },
  { value: "⚙️", keywords: ["gear", "settings", "config"] },
  { value: "🔧", keywords: ["wrench", "tool", "fix"] },
  { value: "🔨", keywords: ["hammer", "build", "tool"] },
  { value: "🛠️", keywords: ["tools", "hammer", "wrench", "build"] },
  { value: "🪛", keywords: ["screwdriver", "tool", "fix"] },
  { value: "🔩", keywords: ["bolt", "nut", "hardware"] },
  { value: "🧰", keywords: ["toolbox", "tools", "kit"] },
  { value: "📦", keywords: ["package", "box", "shipping", "npm"] },
  { value: "🧩", keywords: ["puzzle", "piece", "plugin"] },
  { value: "🎲", keywords: ["dice", "game", "random"] },
  { value: "🎮", keywords: ["game", "controller", "play"] },
  { value: "🕹️", keywords: ["joystick", "arcade", "game"] },
  { value: "🃏", keywords: ["joker", "card", "wild"] },
  { value: "♟️", keywords: ["chess", "pawn", "strategy"] },
  { value: "🔑", keywords: ["key", "auth", "access"] },
  { value: "🔒", keywords: ["lock", "security", "private"] },
  { value: "🛡️", keywords: ["shield", "security", "protect"] },
  { value: "🔍", keywords: ["magnifier", "search", "find"] },
  { value: "🔔", keywords: ["bell", "notification", "alert"] },
  { value: "📣", keywords: ["megaphone", "announce", "marketing"] },
  { value: "📈", keywords: ["chart", "growth", "up", "stocks"] },
  { value: "📉", keywords: ["chart", "down", "decline"] },
  { value: "📊", keywords: ["bar chart", "stats", "analytics"] },
  { value: "🧮", keywords: ["abacus", "math", "count"] },
  { value: "💰", keywords: ["money", "bag", "rich"] },
  { value: "💳", keywords: ["credit card", "payment", "billing"] },
  { value: "🏦", keywords: ["bank", "finance"] },
  { value: "🪙", keywords: ["coin", "money", "crypto"] },
  { value: "💼", keywords: ["briefcase", "work", "business"] },
  { value: "🛒", keywords: ["cart", "shopping", "ecommerce"] },
  { value: "🏪", keywords: ["store", "shop", "convenience"] },
  { value: "🏗️", keywords: ["construction", "crane", "build"] },
  { value: "🏠", keywords: ["home", "house"] },
  { value: "🏢", keywords: ["office", "building", "company"] },
  { value: "🏰", keywords: ["castle", "fortress", "kingdom"] },
  { value: "⛺", keywords: ["tent", "camp", "outdoors"] },
  { value: "🎪", keywords: ["circus", "tent", "show"] },
  { value: "🎁", keywords: ["gift", "present", "reward"] },
  { value: "🎈", keywords: ["balloon", "party", "celebrate"] },
  { value: "🎉", keywords: ["party", "confetti", "celebrate"] },
  { value: "🎨", keywords: ["palette", "art", "design"] },
  { value: "🖌️", keywords: ["paintbrush", "art", "paint"] },
  { value: "✏️", keywords: ["pencil", "write", "draft"] },
  { value: "🖊️", keywords: ["pen", "write", "sign"] },
  { value: "📝", keywords: ["memo", "notes", "write"] },
  { value: "📚", keywords: ["books", "library", "docs"] },
  { value: "📖", keywords: ["book", "open", "read"] },
  { value: "📓", keywords: ["notebook", "journal"] },
  { value: "🎓", keywords: ["graduation", "school", "learn"] },
  { value: "🧠", keywords: ["brain", "think", "smart", "ai"] },
  { value: "👀", keywords: ["eyes", "look", "watch"] },
  { value: "🦾", keywords: ["mechanical arm", "bionic", "strong"] },
  { value: "🦄", keywords: ["unicorn", "magic", "startup"] },
  { value: "🐉", keywords: ["dragon", "mythical"] },
  { value: "🐙", keywords: ["octopus", "tentacle", "github"] },
  { value: "🦑", keywords: ["squid", "ocean"] },
  { value: "🐳", keywords: ["whale", "ocean", "docker"] },
  { value: "🐬", keywords: ["dolphin", "ocean"] },
  { value: "🦈", keywords: ["shark", "ocean"] },
  { value: "🐢", keywords: ["turtle", "slow", "steady"] },
  { value: "🐍", keywords: ["snake", "python"] },
  { value: "🦀", keywords: ["crab", "rust"] },
  { value: "🐹", keywords: ["hamster", "pet", "go"] },
  { value: "🐰", keywords: ["rabbit", "bunny", "fast"] },
  { value: "🦊", keywords: ["fox", "clever", "firefox"] },
  { value: "🐺", keywords: ["wolf", "pack"] },
  { value: "🦉", keywords: ["owl", "wise", "night"] },
  { value: "🦅", keywords: ["eagle", "bird", "soar"] },
  { value: "🐝", keywords: ["bee", "busy", "hive"] },
  { value: "🐞", keywords: ["ladybug", "bug", "beetle"] },
  { value: "🕷️", keywords: ["spider", "web", "crawler"] },
  { value: "🦋", keywords: ["butterfly", "transform"] },
  { value: "🐘", keywords: ["elephant", "postgres", "memory"] },
  { value: "🦁", keywords: ["lion", "brave", "king"] },
  { value: "🐯", keywords: ["tiger", "fierce"] },
  { value: "🐼", keywords: ["panda", "bear", "cute"] },
  { value: "🐨", keywords: ["koala", "australia"] },
  { value: "🐸", keywords: ["frog", "green"] },
  { value: "🐦", keywords: ["bird", "tweet"] },
  { value: "🐈", keywords: ["cat", "kitten", "pet"] },
  { value: "🐕", keywords: ["dog", "puppy", "pet"] },
  { value: "☕", keywords: ["coffee", "cup", "java"] },
  { value: "🍵", keywords: ["tea", "cup", "matcha"] },
  { value: "🍕", keywords: ["pizza", "slice", "food"] },
  { value: "🍔", keywords: ["burger", "food"] },
  { value: "🌮", keywords: ["taco", "food", "mexican"] },
  { value: "🍜", keywords: ["ramen", "noodles", "soup"] },
  { value: "🍩", keywords: ["donut", "doughnut", "sweet"] },
  { value: "🍪", keywords: ["cookie", "biscuit", "sweet"] },
  { value: "🎂", keywords: ["cake", "birthday", "celebrate"] },
  { value: "🍎", keywords: ["apple", "fruit", "red"] },
  { value: "🍋", keywords: ["lemon", "citrus", "sour"] },
  { value: "🍉", keywords: ["watermelon", "fruit", "summer"] },
  { value: "🍇", keywords: ["grapes", "fruit", "wine"] },
  { value: "🥑", keywords: ["avocado", "green", "healthy"] },
  { value: "🌶️", keywords: ["pepper", "chili", "spicy", "hot"] },
  { value: "🎵", keywords: ["music", "note", "song"] },
  { value: "🎧", keywords: ["headphones", "audio", "listen"] },
  { value: "🎤", keywords: ["microphone", "sing", "podcast"] },
  { value: "🎬", keywords: ["clapper", "movie", "film"] },
  { value: "📷", keywords: ["camera", "photo"] },
  { value: "🎹", keywords: ["piano", "keyboard", "music"] },
  { value: "🥁", keywords: ["drum", "beat", "music"] },
  { value: "🎸", keywords: ["guitar", "rock", "music"] },
  { value: "🧘", keywords: ["meditation", "yoga", "calm"] },
  { value: "🏃", keywords: ["run", "running", "fast"] },
  { value: "🏋️", keywords: ["weights", "gym", "lift"] },
  { value: "⚽", keywords: ["soccer", "football", "ball"] },
  { value: "🏀", keywords: ["basketball", "ball", "hoops"] },
  { value: "🎾", keywords: ["tennis", "ball", "racket"] },
  { value: "🏈", keywords: ["football", "american", "ball"] },
  { value: "⚾", keywords: ["baseball", "ball"] },
  { value: "🎳", keywords: ["bowling", "pins", "strike"] },
  { value: "🛹", keywords: ["skateboard", "skate"] },
  { value: "⛵", keywords: ["sailboat", "sail", "boat"] },
  { value: "🏴‍☠️", keywords: ["pirate", "flag", "jolly roger"] },
  { value: "🚧", keywords: ["construction", "wip", "barrier"] },
  { value: "🧨", keywords: ["dynamite", "explosive", "tnt"] },
  { value: "💣", keywords: ["bomb", "explode"] },
  { value: "🕳️", keywords: ["hole", "void"] },
  { value: "🧿", keywords: ["nazar", "evil eye", "amulet"] },
  { value: "🔮", keywords: ["crystal ball", "future", "magic"] },
  { value: "🧙", keywords: ["wizard", "mage", "magic"] },
  { value: "🥷", keywords: ["ninja", "stealth"] },
  { value: "🦸", keywords: ["superhero", "hero", "cape"] },
  { value: "🧊", keywords: ["ice", "cube", "cold"] },
  { value: "❄️", keywords: ["snowflake", "winter", "cold"] },
  { value: "☂️", keywords: ["umbrella", "rain"] },
  { value: "🌪️", keywords: ["tornado", "storm", "twister"] },
  { value: "🫧", keywords: ["bubbles", "clean", "soap"] },
  { value: "💧", keywords: ["droplet", "water", "drop"] },
] as const;

export function projectGlyph(name: string): ProjectGlyph | null {
  return GLYPH_BY_NAME.get(name) ?? null;
}

export function ProjectGlyphIcon({
  name,
  className,
  "aria-hidden": ariaHidden,
  "aria-label": ariaLabel,
}: {
  name: string;
  className?: string;
  "aria-hidden"?: boolean | "true" | "false";
  "aria-label"?: string;
}) {
  const glyph = GLYPH_BY_NAME.get(name);
  if (!glyph) return null;
  return (
    <HugeiconsIcon
      icon={glyph.icon}
      className={cn(className)}
      aria-hidden={ariaHidden}
      aria-label={ariaLabel}
      data-project-glyph={name}
    />
  );
}

export function filterProjectGlyphs(
  query: string,
): readonly ProjectGlyph[] {
  const normalized = query.trim().toLocaleLowerCase();
  if (!normalized) return PROJECT_GLYPHS;
  return PROJECT_GLYPHS.filter(
    (glyph) =>
      glyph.name.toLocaleLowerCase().includes(normalized) ||
      glyph.keywords.some((keyword) => keyword.includes(normalized)),
  );
}

export function filterProjectEmoji(query: string): readonly ProjectEmoji[] {
  const normalized = query.trim().toLocaleLowerCase();
  if (!normalized) return PROJECT_EMOJI;
  return PROJECT_EMOJI.filter((emoji) =>
    emoji.keywords.some((keyword) => keyword.includes(normalized)),
  );
}
